#ifndef __CORE_MESSAGE_H__
#define __CORE_MESSAGE_H__


struct Header {

    uint16_t magic;         // tk 0x74 0x6b
    uint16_t version;       // 0x01
    uint16_t message_len;   // playload length (not include header)
    uint64_t message_id;    // generated by sender

} __attributed__ ((packed));

class Message {

};

#endif // __CORE_MESSAGE_H__
